const replacements: Array<[string, string]> = [
  ['任务已创建，等待处理...', 'Task created, waiting to start...'],
  ['正在启动翻译任务...', 'Starting translation task...'],
  ['初始化中...', 'Initializing...'],
  ['开始音频分离...', 'Starting audio separation...'],
  ['音频分离中 (', 'Audio separation in progress ('],
  ['音频分离中', 'Audio separation in progress'],
  ['音频分离完成', 'Audio separation completed'],
  ['开始语音识别...', 'Starting speech recognition...'],
  ['识别完成，共 ', 'Recognition completed, '],
  ['开始翻译 ', 'Starting translation: '],
  ['翻译中 (', 'Translating ('],
  ['翻译中 ', 'Translating '],
  ['翻译完成', 'Translation completed'],
  ['参考音频提取完成，', 'Reference audio extraction completed, '],
  ['音色克隆中 (', 'Voice cloning in progress ('],
  ['音色克隆中 ', 'Voice cloning in progress '],
  ['音频合并中 (', 'Audio merging in progress ('],
  ['音频合并中 ', 'Audio merging in progress '],
  ['视频合成中 (', 'Video synthesis in progress ('],
  ['视频合成中 ', 'Video synthesis in progress '],
  ['处理中...', 'Processing...'],
  ['已完成', 'Completed'],
  ['处理中', 'Processing'],
  ['等待中', 'Pending'],
  ['失败', 'Failed'],
  ['待编辑分段', 'Awaiting segment review'],
  ['待编辑翻译', 'Awaiting translation review'],
  ['步骤1: 音频提取开始...', 'Step 1: Audio extraction starting...'],
  ['步骤1:音频提取开始...', 'Step 1: Audio extraction starting...'],
  ['步骤2: 音频分离开始...', 'Step 2: Audio separation starting...'],
  ['步骤2:音频分离开始...', 'Step 2: Audio separation starting...'],
  ['步骤3: 人声分离开始...', 'Step 3: Vocal separation starting...'],
  ['步骤3:人声分离开始...', 'Step 3: Vocal separation starting...'],
  ['步骤3: 多说话人处理开始...', 'Step 3: Speaker diarization starting...'],
  ['步骤3:多说话人处理开始...', 'Step 3: Speaker diarization starting...'],
  ['步骤4: 语音识别开始...', 'Step 4: Speech recognition starting...'],
  ['步骤4:语音识别开始...', 'Step 4: Speech recognition starting...'],
  ['步骤5: 文本翻译开始...', 'Step 5: Text translation starting...'],
  ['步骤5:文本翻译开始...', 'Step 5: Text translation starting...'],
  ['步骤6: 参考音频提取开始...', 'Step 6: Reference audio extraction starting...'],
  ['步骤6:参考音频提取开始...', 'Step 6: Reference audio extraction starting...'],
  ['步骤7: 音色克隆开始...', 'Step 7: Voice cloning starting...'],
  ['步骤7:音色克隆开始...', 'Step 7: Voice cloning starting...'],
  ['步骤8: 音频合并开始...', 'Step 8: Audio merging starting...'],
  ['步骤8:音频合并开始...', 'Step 8: Audio merging starting...'],
  ['步骤9: 视频合成开始...', 'Step 9: Video synthesis starting...'],
  ['步骤9:视频合成开始...', 'Step 9: Video synthesis starting...'],
  ['步骤10: 视频合成开始...', 'Step 10: Video synthesis starting...'],
  ['步骤10:视频合成开始...', 'Step 10: Video synthesis starting...'],
  ['步骤1: 音频提取', 'Step 1: Audio extraction'],
  ['步骤1:音频提取', 'Step 1: Audio extraction'],
  ['步骤2: 音频分离', 'Step 2: Audio separation'],
  ['步骤2:音频分离', 'Step 2: Audio separation'],
  ['步骤3: 人声分离', 'Step 3: Vocal separation'],
  ['步骤3:人声分离', 'Step 3: Vocal separation'],
  ['步骤3: 多说话人处理', 'Step 3: Speaker diarization'],
  ['步骤3:多说话人处理', 'Step 3: Speaker diarization'],
  ['步骤4: 语音识别', 'Step 4: Speech recognition'],
  ['步骤4:语音识别', 'Step 4: Speech recognition'],
  ['步骤5: 文本翻译', 'Step 5: Text translation'],
  ['步骤5:文本翻译', 'Step 5: Text translation'],
  ['步骤6: 参考音频提取', 'Step 6: Reference audio extraction'],
  ['步骤6:参考音频提取', 'Step 6: Reference audio extraction'],
  ['步骤7: 音色克隆', 'Step 7: Voice cloning'],
  ['步骤7:音色克隆', 'Step 7: Voice cloning'],
  ['步骤8: 音频合并', 'Step 8: Audio merging'],
  ['步骤8:音频合并', 'Step 8: Audio merging'],
  ['步骤9: 视频合成', 'Step 9: Video synthesis'],
  ['步骤9:视频合成', 'Step 9: Video synthesis'],
  ['步骤10: 视频合成', 'Step 10: Video synthesis'],
  ['步骤10:视频合成', 'Step 10: Video synthesis'],
  ['步骤10', 'Step 10'],
  ['步骤1', 'Step 1'],
  ['步骤2', 'Step 2'],
  ['步骤3', 'Step 3'],
  ['步骤4', 'Step 4'],
  ['步骤5', 'Step 5'],
  ['步骤6', 'Step 6'],
  ['步骤7', 'Step 7'],
  ['步骤8', 'Step 8'],
  ['步骤9', 'Step 9'],
  ['正在处理第 ', 'Processing segment '],
  [' 个片段，共 ', ' of '],
  [' 个片段...', ' segments...'],
  [' 个段落...', ' segments...'],
  [' 个片段', ' segments'],
  [' 个段落', ' segments'],
  ['个片段', ' segments'],
  ['个段落', ' segments'],
  ['音频提取', 'Audio extraction'],
  ['人声分离', 'Vocal separation'],
  ['多说话人处理', 'Speaker diarization'],
  ['语音识别', 'Speech recognition'],
  ['文本翻译', 'Text translation'],
  ['参考音频提取', 'Reference audio extraction'],
  ['音色克隆', 'Voice cloning'],
  ['音频合并', 'Audio merging'],
  ['视频合成', 'Video synthesis'],
  ['片段', 'segment'],
  ['开始', 'Starting'],
  ['完成', 'completed'],
];

export const translateTaskText = (text?: string | null): string => {
  if (!text) return '';

  return replacements.reduce((current, [from, to]) => {
    return current.split(from).join(to);
  }, text);
};
